using MudBlazor;

namespace Umbra.School.Shared
{
    public static class MudThemes
    {
        /*
        !
        * Bootswatch v5.3.3 (https://bootswatch.com)
        * Theme: flatly
        * Copyright 2012-2024 Thomas Park
        * Licensed under MIT
        * Based on Bootstrap
        */
        public static readonly MudTheme Flatlytheme = new()
        {
            PaletteLight = new PaletteLight()
            {
                TableHover = "rgba(0,0,0,0.0392156862745098)",
                OverlayLight = "rgba(255,255,255,0.4980392156862745)",
                OverlayDark = "rgba(33,33,33,0.4980392156862745)",
                GrayDarker = "#616161",
                GrayDark = "#757575",
                GrayLighter = "#E0E0E0",
                GrayLight = "#BDBDBD",
                GrayDefault = "#9E9E9E",
                RippleOpacitySecondary = 0.2,
                RippleOpacity = 0.1,
                HoverOpacity = 0.06,
                Surface = "rgba(255,255,255,1)",
                Background = "rgba(255,255,255,1)",
                BackgroundGray = "rgba(245,245,245,1)",
                ErrorContrastText = "rgba(255,255,255,1)",
                LinesInputs = "rgba(189,189,189,1)",
                ActionDisabled = "rgba(0,0,0,0.25882352941176473)",
                TextDisabled = "rgba(0,0,0,0.3764705882352941)",
                TableStriped = "rgba(0,0,0,0.0196078431372549)",
                LinesDefault = "rgba(0,0,0,0.11764705882352941)",
                ActionDisabledBackground = "rgba(0,0,0,0.11764705882352941)",
                TableLines = "rgba(224,224,224,1)",
                Divider = "rgba(224,224,224,1)",
                DividerLight = "rgba(0,0,0,0.8)",
                Error = "rgba(244,67,54,1)",
                TertiaryLighten = "rgba(33, 37, 41, 0.5)",
                Tertiary = "rgba(33, 37, 41, 0.5)",
                TertiaryDarken = "rgba(33, 37, 41, 0.5)",
                ActionDefault = "rgba(0,0,0,0.5372549019607843)",
                DarkLighten = "rgb(87,87,87)",
                ErrorLighten = "rgb(246,96,85)",
                ErrorDarken = "rgb(242,28,13)",
                DarkDarken = "rgb(46,46,46)",
                PrimaryContrastText = "#d5d8dc",
                SecondaryContrastText = "#eaeded",
                TertiaryContrastText = "#f8f9fa",
                White = "#fff",
                WarningDarken = "#613e07",
                Warning = "#f39c12",
                SecondaryDarken = "#3c4242",
                TextSecondary = "#3c4242",
                Secondary = "#95a5a6",
                DrawerIcon = "#95a5a6",
                DrawerText = "#95a5a6",
                InfoDarken = "#153d58",
                PrimaryDarken = "#121920",
                TextPrimary = "#121920",
                Dark = "#7b8a8b",
                SuccessDarken = "#0a4b3e",
                Info = "#3498db",
                WarningLighten = "#fdebd0",
                WarningContrastText = "#fdebd0",
                Primary = "#2c3e50",
                AppbarText = "#2c3e50",
                SecondaryLighten = "#eaeded",
                DrawerBackground = "#eaeded",
                DarkContrastText = "#ced4da",
                Success = "#18bc9c",
                InfoLighten = "#d6eaf8",
                InfoContrastText = "#d6eaf8",
                PrimaryLighten = "#d5d8dc",
                AppbarBackground = "#d5d8dc",
                SuccessContrastText = "#d1f2eb",
                SuccessLighten = "#d1f2eb",
                Black = "#000",
            },
            PaletteDark = new PaletteDark()
            {
                Surface = "rgba(55,55,64,1)",
                Background = "rgba(50,51,61,1)",
                BackgroundGray = "rgba(39,39,47,1)",
                ErrorContrastText = "rgba(255,255,255,1)",
                LinesInputs = "rgba(255,255,255,0.2980392156862745)",
                ActionDisabled = "rgba(255,255,255,0.25882352941176473)",
                TextDisabled = "rgba(255,255,255,0.2)",
                TableStriped = "rgba(255,255,255,0.2)",
                LinesDefault = "rgba(255,255,255,0.11764705882352941)",
                ActionDisabledBackground = "rgba(255,255,255,0.11764705882352941)",
                TableLines = "rgba(255,255,255,0.11764705882352941)",
                Divider = "rgba(255,255,255,0.11764705882352941)",
                DividerLight = "rgba(255,255,255,0.058823529411764705)",
                Error = "rgba(244,67,54,1)",
                TertiaryLighten = "rgba(222, 226, 230, 0.5)",
                Tertiary = "rgba(222, 226, 230, 0.5)",
                TertiaryDarken = "rgba(222, 226, 230, 0.5)",
                ActionDefault = "rgba(173,173,177,1)",
                DarkLighten = "rgb(56,56,67)",
                ErrorLighten = "rgb(246,96,85)",
                ErrorDarken = "rgb(242,28,13)",
                DarkDarken = "rgb(23,23,28)",
                PrimaryContrastText = "#ffffffff",
                SecondaryContrastText = "#ffffffff",
                TertiaryContrastText = "#ffffffff",
                White = "#fff",
                WarningDarken = "#f8c471",
                Warning = "#f39c12",
                SecondaryDarken = "#bfc9ca",
                TextSecondary = "#bfc9ca",
                Secondary = "#95a5a6",
                DrawerIcon = "#95a5a6",
                DrawerText = "#95a5a6",
                InfoDarken = "#85c1e9",
                PrimaryDarken = "#808b96",
                TextPrimary = "#808b96",
                Dark = "#7b8a8b",
                SuccessDarken = "#74d7c4",
                Info = "#3498db",
                WarningLighten = "#311f04",
                WarningContrastText = "#311f04",
                Primary = "#2c3e50",
                AppbarText = "#2c3e50",
                SecondaryLighten = "#1e2121",
                DrawerBackground = "#1e2121",
                DarkContrastText = "#1a1d20",
                Success = "#18bc9c",
                InfoLighten = "#0a1e2c",
                InfoContrastText = "#0a1e2c",
                PrimaryLighten = "#090c10",
                AppbarBackground = "#090c10",
                SuccessContrastText = "#05261f",
                SuccessLighten = "#05261f",
                Black = "#000",
            },
            LayoutProperties = new LayoutProperties()
            {
                AppbarHeight = "64px",
                DefaultBorderRadius = "4px",
                DrawerMiniWidthLeft = "56px",
                DrawerMiniWidthRight = "56px",
                DrawerWidthLeft = "240px",
                DrawerWidthRight = "240px",
            },
            Typography = new Typography()
            {
                Default = new DefaultTypography
                {
                    FontFamily = ["Roboto", "Helvetica", "Arial", "sans-serif"],
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                H1 = new H1Typography
                {
                    FontWeight = "300",
                    FontSize = "6rem",
                    LineHeight = "1.167",
                    LetterSpacing = "-.01562em",
                    TextTransform = "none",
                },
                H2 = new H2Typography
                {
                    FontWeight = "300",
                    FontSize = "3.75rem",
                    LineHeight = "1.2",
                    LetterSpacing = "-.00833em",
                    TextTransform = "none",
                },
                H3 = new H3Typography
                {
                    FontWeight = "400",
                    FontSize = "3rem",
                    LineHeight = "1.167",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H4 = new H4Typography
                {
                    FontWeight = "400",
                    FontSize = "2.125rem",
                    LineHeight = "1.235",
                    LetterSpacing = ".00735em",
                    TextTransform = "none",
                },
                H5 = new H5Typography
                {
                    FontWeight = "400",
                    FontSize = "1.5rem",
                    LineHeight = "1.334",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H6 = new H6Typography
                {
                    FontWeight = "500",
                    FontSize = "1.25rem",
                    LineHeight = "1.6",
                    LetterSpacing = ".0075em",
                    TextTransform = "none",
                },
                Subtitle1 = new Subtitle1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Subtitle2 = new Subtitle2Typography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.57",
                    LetterSpacing = ".00714em",
                    TextTransform = "none",
                },
                Body1 = new Body1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.5",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Body2 = new Body2Typography
                {
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                Button = new ButtonTypography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".02857em",
                    TextTransform = "uppercase",
                },
                Caption = new CaptionTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "1.66",
                    LetterSpacing = ".03333em",
                    TextTransform = "none",
                },
                Overline = new OverlineTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "2.66",
                    LetterSpacing = ".08333em",
                    TextTransform = "none",
                },
            },
            ZIndex = new ZIndex()
            {
                AppBar = 1300,
                Dialog = 1400,
                Drawer = 1100,
                Popover = 1200,
                Snackbar = 1500,
                Tooltip = 1600,
            },
        };


        /* 
        !
         * Bootswatch v5.3.3 (https://bootswatch.com)
         * Theme: journal
         * Copyright 2012-2024 Thomas Park
         * Licensed under MIT
         * Based on Bootstrap
         */
        public static readonly MudTheme Journaltheme = new()
        {
            PaletteLight = new PaletteLight()
            {
                TableHover = "rgba(0,0,0,0.0392156862745098)",
                OverlayLight = "rgba(255,255,255,0.4980392156862745)",
                OverlayDark = "rgba(33,33,33,0.4980392156862745)",
                GrayDarker = "#616161",
                GrayDark = "#757575",
                GrayLighter = "#E0E0E0",
                GrayLight = "#BDBDBD",
                GrayDefault = "#9E9E9E",
                RippleOpacitySecondary = 0.2,
                RippleOpacity = 0.1,
                HoverOpacity = 0.06,
                Surface = "rgba(230,233,235,1)",
                Background = "rgba(255,255,255,1)",
                BackgroundGray = "rgba(245,245,245,1)",
                ErrorContrastText = "rgba(255,255,255,1)",
                LinesInputs = "rgba(189,189,189,1)",
                ActionDisabled = "rgba(0,0,0,0.25882352941176473)",
                TextDisabled = "rgba(0,0,0,0.3764705882352941)",
                TableStriped = "rgba(0,0,0,0.0196078431372549)",
                LinesDefault = "rgba(0,0,0,0.11764705882352941)",
                ActionDisabledBackground = "rgba(0,0,0,0.11764705882352941)",
                TableLines = "rgba(224,224,224,1)",
                Divider = "rgba(224,224,224,1)",
                DividerLight = "rgba(0,0,0,0.8)",
                Error = "rgba(244,67,54,1)",
                TertiaryDarken = "rgba(34, 34, 34, 0.5)",
                Tertiary = "rgba(34, 34, 34, 0.5)",
                TertiaryLighten = "rgba(34, 34, 34, 0.5)",
                ActionDefault = "rgba(0,0,0,0.5372549019607843)",
                DarkLighten = "rgb(87,87,87)",
                ErrorLighten = "rgb(246,96,85)",
                ErrorDarken = "rgb(242,28,13)",
                DarkDarken = "rgb(46,46,46)",
                White = "#fff",
                WarningDarken = "#625c0f",
                Warning = "#f5e625",
                TextPrimary = "#5e2a28",
                PrimaryDarken = "#5e2a28",
                Primary = "#eb6864",
                AppbarText = "#eb6864",
                SecondaryDarken = "#444444",
                TextSecondary = "#444444",
                Secondary = "#aaa",
                DrawerText = "#aaa",
                DrawerIcon = "#aaa",
                DarkContrastText = "#ced4da",
                InfoDarken = "#14293d",
                SuccessDarken = "#0e471e",
                Info = "#369",
                WarningContrastText = "#fdfad3",
                WarningLighten = "#fdfad3",
                PrimaryContrastText = "#fbe1e0",
                PrimaryLighten = "#fbe1e0",
                AppbarBackground = "#fbe1e0",
                TertiaryContrastText = "#f8f9fa",
                Success = "#22b24c",
                SecondaryContrastText = "#eeeeee",
                SecondaryLighten = "#eeeeee",
                DrawerBackground = "#eeeeee",
                Dark = "#222",
                InfoLighten = "#d6e0eb",
                InfoContrastText = "#d6e0eb",
                SuccessContrastText = "#d3f0db",
                SuccessLighten = "#d3f0db",
                Black = "#000",
            },
            PaletteDark = new PaletteDark()
            {
                Surface = "rgba(55,55,64,1)",
                Background = "rgba(50,51,61,1)",
                BackgroundGray = "rgba(39,39,47,1)",
                ErrorContrastText = "rgba(255,255,255,1)",
                LinesInputs = "rgba(255,255,255,0.2980392156862745)",
                ActionDisabled = "rgba(255,255,255,0.25882352941176473)",
                TextDisabled = "rgba(255,255,255,0.2)",
                TableStriped = "rgba(255,255,255,0.2)",
                LinesDefault = "rgba(255,255,255,0.11764705882352941)",
                ActionDisabledBackground = "rgba(255,255,255,0.11764705882352941)",
                TableLines = "rgba(255,255,255,0.11764705882352941)",
                Divider = "rgba(255,255,255,0.11764705882352941)",
                DividerLight = "rgba(255,255,255,0.058823529411764705)",
                Error = "rgba(244,67,54,1)",
                TertiaryDarken = "rgba(222, 226, 230, 0.5)",
                Tertiary = "rgba(222, 226, 230, 0.5)",
                TertiaryLighten = "rgba(222, 226, 230, 0.5)",
                ActionDefault = "rgba(173,173,177,1)",
                DarkLighten = "rgb(56,56,67)",
                ErrorLighten = "rgb(246,96,85)",
                ErrorDarken = "rgb(242,28,13)",
                DarkDarken = "rgb(23,23,28)",
                White = "#fff",
                WarningDarken = "#f9f07c",
                Warning = "#f5e625",
                TextPrimary = "#f3a4a2",
                PrimaryDarken = "#f3a4a2",
                Primary = "#eb6864",
                AppbarText = "#eb6864",
                SecondaryDarken = "#cccccc",
                TextSecondary = "#cccccc",
                Secondary = "#aaa",
                DrawerText = "#aaa",
                DrawerIcon = "#aaa",
                DarkContrastText = "#a2a2a2ff",
                InfoDarken = "#85a3c2",
                SuccessDarken = "#7ad194",
                Info = "#369",
                WarningContrastText = "#312e07",
                WarningLighten = "#312e07",
                PrimaryContrastText = "#2f1514",
                PrimaryLighten = "#2f1514",
                AppbarBackground = "#2f1514",
                TertiaryContrastText = "#2b2b2b",
                Success = "#22b24c",
                SecondaryContrastText = "#222222",
                SecondaryLighten = "#222222",
                DrawerBackground = "#222222",
                Dark = "#222",
                InfoLighten = "#0a141f",
                InfoContrastText = "#0a141f",
                SuccessContrastText = "#07240f",
                SuccessLighten = "#07240f",
                Black = "#000",
            },
            LayoutProperties = new LayoutProperties()
            {
                AppbarHeight = "64px",
                DefaultBorderRadius = "4px",
                DrawerMiniWidthLeft = "56px",
                DrawerMiniWidthRight = "56px",
                DrawerWidthLeft = "240px",
                DrawerWidthRight = "240px",
            },
            Typography = new Typography()
            {
                Default = new DefaultTypography
                {
                    FontFamily = ["Roboto", "Helvetica", "Arial", "sans-serif"],
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                H1 = new H1Typography
                {
                    FontWeight = "300",
                    FontSize = "6rem",
                    LineHeight = "1.167",
                    LetterSpacing = "-.01562em",
                    TextTransform = "none",
                },
                H2 = new H2Typography
                {
                    FontWeight = "300",
                    FontSize = "3.75rem",
                    LineHeight = "1.2",
                    LetterSpacing = "-.00833em",
                    TextTransform = "none",
                },
                H3 = new H3Typography
                {
                    FontWeight = "400",
                    FontSize = "3rem",
                    LineHeight = "1.167",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H4 = new H4Typography
                {
                    FontWeight = "400",
                    FontSize = "2.125rem",
                    LineHeight = "1.235",
                    LetterSpacing = ".00735em",
                    TextTransform = "none",
                },
                H5 = new H5Typography
                {
                    FontWeight = "400",
                    FontSize = "1.5rem",
                    LineHeight = "1.334",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H6 = new H6Typography
                {
                    FontWeight = "500",
                    FontSize = "1.25rem",
                    LineHeight = "1.6",
                    LetterSpacing = ".0075em",
                    TextTransform = "none",
                },
                Subtitle1 = new Subtitle1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Subtitle2 = new Subtitle2Typography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.57",
                    LetterSpacing = ".00714em",
                    TextTransform = "none",
                },
                Body1 = new Body1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.5",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Body2 = new Body2Typography
                {
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                Button = new ButtonTypography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".02857em",
                    TextTransform = "uppercase",
                },
                Caption = new CaptionTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "1.66",
                    LetterSpacing = ".03333em",
                    TextTransform = "none",
                },
                Overline = new OverlineTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "2.66",
                    LetterSpacing = ".08333em",
                    TextTransform = "none",
                },
            },
            ZIndex = new ZIndex()
            {
                AppBar = 1300,
                Dialog = 1400,
                Drawer = 1100,
                Popover = 1200,
                Snackbar = 1500,
                Tooltip = 1600,
            },
        };

        /* 
        !
        * Bootswatch v5.3.3 (https://bootswatch.com)
        * Theme: pulse
        * Copyright 2012-2024 Thomas Park
        * Licensed under MIT
        * Based on Bootstrap
        */
        public static readonly MudTheme Pulsetheme = new()
        {
            PaletteLight = new PaletteLight()
            {
                TableHover = "rgba(0,0,0,0.0392156862745098)",
                OverlayLight = "rgba(255,255,255,0.4980392156862745)",
                OverlayDark = "rgba(33,33,33,0.4980392156862745)",
                GrayDarker = "#616161",
                GrayDark = "#757575",
                GrayLighter = "#E0E0E0",
                GrayLight = "#BDBDBD",
                GrayDefault = "#9E9E9E",
                RippleOpacitySecondary = 0.2,
                RippleOpacity = 0.1,
                HoverOpacity = 0.06,
                Surface = "rgba(255,255,255,1)",
                Background = "rgba(255,255,255,1)",
                BackgroundGray = "rgba(245,245,245,1)",
                ErrorContrastText = "rgba(255,255,255,1)",
                LinesInputs = "rgba(189,189,189,1)",
                ActionDisabled = "rgba(0,0,0,0.25882352941176473)",
                TextDisabled = "rgba(0,0,0,0.3764705882352941)",
                TableStriped = "rgba(0,0,0,0.0196078431372549)",
                LinesDefault = "rgba(0,0,0,0.11764705882352941)",
                ActionDisabledBackground = "rgba(0,0,0,0.11764705882352941)",
                TableLines = "rgba(224,224,224,1)",
                Divider = "rgba(224,224,224,1)",
                DividerLight = "rgba(0,0,0,0.8)",
                Error = "rgba(244,67,54,1)",
                TertiaryDarken = "rgba(68, 68, 68, 0.5)",
                Tertiary = "rgba(68, 68, 68, 0.5)",
                TertiaryLighten = "rgba(68, 68, 68, 0.5)",
                ActionDefault = "rgba(0,0,0,0.5372549019607843)",
                DarkLighten = "rgb(87,87,87)",
                ErrorLighten = "rgb(246,96,85)",
                ErrorDarken = "rgb(242,28,13)",
                DarkDarken = "rgb(46,46,46)",
                White = "#fff",
                WarningDarken = "#60410c",
                Warning = "#efa31d",
                DarkContrastText = "#cbc8d0",
                PrimaryContrastText = "#ded6ea",
                SecondaryDarken = "#8976abff",
                TextSecondary = "#443a55",
                Secondary = "#ffffffff",
                DrawerText = "#a991d4",
                DrawerIcon = "#a991d4",
                TextPrimary = "#24143c",
                PrimaryDarken = "#8976abff",
                SuccessDarken = "#084a22",
                InfoDarken = "#003e58",
                Primary = "#593196",
                AppbarText = "#593196",
                WarningLighten = "#fcedd2",
                WarningContrastText = "#fcedd2",
                TertiaryContrastText = "#fafafa",
                SecondaryContrastText = "#333333ff",
                SecondaryLighten = "#eee9f6",
                DrawerBackground = "#eee9f6",
                Dark = "#17141f",
                Success = "#13b955",
                PrimaryLighten = "#ded6ea",
                AppbarBackground = "#ded6ea",
                SuccessContrastText = "#d0f1dd",
                SuccessLighten = "#d0f1dd",
                Info = "#009cdc",
                InfoContrastText = "#ccebf8",
                InfoLighten = "#ccebf8",
                Black = "#000",
            },
            PaletteDark = new PaletteDark()
            {
                Surface = "rgba(55,55,64,1)",
                Background = "rgba(50,51,61,1)",
                BackgroundGray = "rgba(39,39,47,1)",
                ErrorContrastText = "rgba(255,255,255,1)",
                LinesInputs = "rgba(255,255,255,0.2980392156862745)",
                ActionDisabled = "rgba(255,255,255,0.25882352941176473)",
                TextDisabled = "rgba(255,255,255,0.2)",
                TableStriped = "rgba(255,255,255,0.2)",
                LinesDefault = "rgba(255,255,255,0.11764705882352941)",
                ActionDisabledBackground = "rgba(255,255,255,0.11764705882352941)",
                TableLines = "rgba(255,255,255,0.11764705882352941)",
                Divider = "rgba(255,255,255,0.11764705882352941)",
                DividerLight = "rgba(255,255,255,0.058823529411764705)",
                Error = "rgba(244,67,54,1)",
                TertiaryDarken = "rgba(237, 237, 237, 0.5)",
                Tertiary = "rgba(237, 237, 237, 0.5)",
                TertiaryLighten = "rgba(237, 237, 237, 0.5)",
                ActionDefault = "rgba(173,173,177,1)",
                DarkLighten = "rgb(56,56,67)",
                ErrorLighten = "rgb(246,96,85)",
                ErrorDarken = "rgb(242,28,13)",
                DarkDarken = "rgb(23,23,28)",
                White = "#fff",
                WarningDarken = "#f5c877",
                Warning = "#efa31d",
                DarkContrastText = "#ebebebff",
                PrimaryContrastText = "#cececeff",
                SecondaryDarken = "#cbbde5",
                TextSecondary = "#cbbde5",
                Secondary = "#c8b8e8ff",
                DrawerText = "#a991d4",
                DrawerIcon = "#a991d4",
                TextPrimary = "#9b83c0",
                PrimaryDarken = "#9b83c0",
                SuccessDarken = "#71d599",
                InfoDarken = "#66c4ea",
                Primary = "#593196",
                AppbarText = "#593196",
                WarningLighten = "#302106",
                WarningContrastText = "#302106",
                TertiaryContrastText = "#262730",
                SecondaryContrastText = "#221d2a",
                SecondaryLighten = "#221d2a",
                DrawerBackground = "#221d2a",
                Dark = "#17141f",
                Success = "#13b955",
                PrimaryLighten = "#120a1e",
                AppbarBackground = "#120a1e",
                SuccessContrastText = "#042511",
                SuccessLighten = "#042511",
                Info = "#009cdc",
                InfoContrastText = "#001f2c",
                InfoLighten = "#001f2c",
                Black = "#000",
            },
            LayoutProperties = new LayoutProperties()
            {
                AppbarHeight = "64px",
                DefaultBorderRadius = "4px",
                DrawerMiniWidthLeft = "56px",
                DrawerMiniWidthRight = "56px",
                DrawerWidthLeft = "240px",
                DrawerWidthRight = "240px",
            },
            Typography = new Typography()
            {
                Default = new DefaultTypography
                {
                    FontFamily = ["Roboto", "Helvetica", "Arial", "sans-serif"],
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                H1 = new H1Typography
                {
                    FontWeight = "300",
                    FontSize = "6rem",
                    LineHeight = "1.167",
                    LetterSpacing = "-.01562em",
                    TextTransform = "none",
                },
                H2 = new H2Typography
                {
                    FontWeight = "300",
                    FontSize = "3.75rem",
                    LineHeight = "1.2",
                    LetterSpacing = "-.00833em",
                    TextTransform = "none",
                },
                H3 = new H3Typography
                {
                    FontWeight = "400",
                    FontSize = "3rem",
                    LineHeight = "1.167",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H4 = new H4Typography
                {
                    FontWeight = "400",
                    FontSize = "2.125rem",
                    LineHeight = "1.235",
                    LetterSpacing = ".00735em",
                    TextTransform = "none",
                },
                H5 = new H5Typography
                {
                    FontWeight = "400",
                    FontSize = "1.5rem",
                    LineHeight = "1.334",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H6 = new H6Typography
                {
                    FontWeight = "500",
                    FontSize = "1.25rem",
                    LineHeight = "1.6",
                    LetterSpacing = ".0075em",
                    TextTransform = "none",
                },
                Subtitle1 = new Subtitle1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Subtitle2 = new Subtitle2Typography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.57",
                    LetterSpacing = ".00714em",
                    TextTransform = "none",
                },
                Body1 = new Body1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.5",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Body2 = new Body2Typography
                {
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                Button = new ButtonTypography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".02857em",
                    TextTransform = "uppercase",
                },
                Caption = new CaptionTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "1.66",
                    LetterSpacing = ".03333em",
                    TextTransform = "none",
                },
                Overline = new OverlineTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "2.66",
                    LetterSpacing = ".08333em",
                    TextTransform = "none",
                },
            },
            ZIndex = new ZIndex()
            {
                AppBar = 1300,
                Dialog = 1400,
                Drawer = 1100,
                Popover = 1200,
                Snackbar = 1500,
                Tooltip = 1600,
            },
        };

        /* 
        Silver Theme (Created by Versile2)
        */
        public static readonly MudTheme Silvertheme = new()
        {
            PaletteLight = new PaletteLight()
            {
                PrimaryContrastText = "#FFFFFF",
                SecondaryContrastText = "#ffffffff",
                TertiaryContrastText = "#FFFFFF",
                TertiaryDarken = "#19a98cff",
                InfoContrastText = "rgba(255,255,255,1)",
                SuccessContrastText = "rgba(255,255,255,1)",
                WarningContrastText = "rgba(255,255,255,1)",
                ErrorContrastText = "rgba(255,255,255,1)",
                DarkContrastText = "rgba(255,255,255,1)",
                RippleOpacitySecondary = 0.2,
                White = "#ffffffff",
                OverlayLight = "#ffffff7f",
                OverlayDark = "#2121217f",
                GrayDarker = "#616161ff",
                GrayDark = "#757575ff",
                GrayLighter = "#e0e0e0ff",
                GrayLight = "#bdbdbdff",
                HoverOpacity = 0.06,
                TableHover = "#0000000a",
                GrayDefault = "#9e9e9eff",
                RippleOpacity = 0.1,
                Surface = "#fdf6f6ff",
                BackgroundGray = "#f5f5f5ff",
                Black = "#594ae2ff",
                LinesInputs = "#bdbdbdff",
                ActionDisabled = "#00000042",
                TableStriped = "#00000033",
                LinesDefault = "#0000001e",
                TableLines = "#e0e0e0ff",
                ActionDisabledBackground = "#0000001e",
                ActionDefault = "#0000008c",
                InfoLighten = "#47a7f5ff",
                SuccessDarken = "#00a344ff",
                WarningLighten = "#ffa724ff",
                ErrorLighten = "#f66055ff",
                ErrorDarken = "#f21c0dff",
                DarkDarken = "#2e2e2eff",
                WarningDarken = "#d68100ff",
                SuccessLighten = "#00eb62ff",
                InfoDarken = "#0c80dfff",
                DrawerIcon = "#000000ff",
                DrawerText = "#000000ff",
                TextPrimary = "#000000ff",
                Warning = "#ff9800",
                DarkLighten = "#ebebebff",
                TextSecondary = "#e0e0e0ff",
                DividerLight = "#dfdedeff",
                Error = "#d92800",
                TextDisabled = "#d0d0d0ff",
                Divider = "#9a9696ff",
                SecondaryLighten = "#7e7e7ee3",
                DrawerBackground = "#798eabff",
                TertiaryLighten = "#59ffdeda",
                PrimaryLighten = "#66c7feff",
                Dark = "#404040",
                Success = "#3ea44e",
                Secondary = "#3b3b3dff",
                AppbarBackground = "#c9cccfff",
                Tertiary = "#2adfbbff",
                Primary = "#1984c8ff",
                PrimaryDarken = "#014f7bff",
                SecondaryDarken = "#060608ff",
                Info = "#007bc3",
                AppbarText = "#ffffffff",
                Background = "#ddddddff",
            },
            PaletteDark = new PaletteDark()
            {
                Surface = "rgba(55,55,64,1)",
                BackgroundGray = "rgba(39,39,47,1)",
                Black = "rgba(39,39,47,1)",
                LinesInputs = "rgba(255,255,255,0.2980392156862745)",
                ActionDisabled = "rgba(255,255,255,0.25882352941176473)",
                TableStriped = "rgba(255,255,255,0.2)",
                LinesDefault = "rgba(255,255,255,0.11764705882352941)",
                TableLines = "rgba(255,255,255,0.11764705882352941)",
                ActionDisabledBackground = "rgba(255,255,255,0.11764705882352941)",
                ActionDefault = "rgba(173,173,177,1)",
                InfoLighten = "rgb(92,173,255)",
                SuccessDarken = "rgb(9,154,108)",
                WarningLighten = "rgb(255,182,36)",
                ErrorLighten = "rgb(248,119,134)",
                ErrorDarken = "rgb(244,47,70)",
                DarkDarken = "rgb(23,23,28)",
                WarningDarken = "rgb(214,143,0)",
                SuccessLighten = "rgb(13,222,156)",
                InfoDarken = "rgb(10,133,255)",
                DrawerIcon = "#ffffffff",
                DrawerText = "#ffffffff",
                TextPrimary = "#ffffff",
                Warning = "#ff9800",
                DarkLighten = "#ebebeb",
                TextSecondary = "#e0e0e0",
                DividerLight = "#dfdedeff",
                Error = "#d92800",
                TextDisabled = "#d0d0d0",
                Divider = "#9a9696ff",
                SecondaryLighten = "#8e8e8eff",
                DrawerBackground = "#798eab",
                TertiaryLighten = "#65fee0ff",
                PrimaryLighten = "#59bdfaff",
                Dark = "#404040",
                Success = "#3ea44e",
                Secondary = "#3b3b3dff",
                AppbarBackground = "#364258",
                Tertiary = "#2adfbbff",
                Primary = "#1984c8",
                PrimaryDarken = "#015284ff",
                SecondaryDarken = "#010103ff",
                Info = "#007bc3",
                AppbarText = "#000000ff",
                Background = "#000000",
            },
            LayoutProperties = new LayoutProperties()
            {
                AppbarHeight = "64px",
                DefaultBorderRadius = "4px",
                DrawerMiniWidthLeft = "56px",
                DrawerMiniWidthRight = "56px",
                DrawerWidthLeft = "240px",
                DrawerWidthRight = "240px",
            },
            Typography = new Typography()
            {
                Default = new DefaultTypography
                {
                    FontFamily = ["Public Sans", "Roboto", "Arial", "sans-serif"],
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                H1 = new H1Typography
                {
                    FontWeight = "300",
                    FontSize = "6rem",
                    LineHeight = "1.167",
                    LetterSpacing = "-.01562em",
                    TextTransform = "none",
                },
                H2 = new H2Typography
                {
                    FontWeight = "300",
                    FontSize = "3.75rem",
                    LineHeight = "1.2",
                    LetterSpacing = "-.00833em",
                    TextTransform = "none",
                },
                H3 = new H3Typography
                {
                    FontWeight = "400",
                    FontSize = "3rem",
                    LineHeight = "1.167",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H4 = new H4Typography
                {
                    FontWeight = "400",
                    FontSize = "2.125rem",
                    LineHeight = "1.235",
                    LetterSpacing = ".00735em",
                    TextTransform = "none",
                },
                H5 = new H5Typography
                {
                    FontWeight = "400",
                    FontSize = "1.5rem",
                    LineHeight = "1.334",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H6 = new H6Typography
                {
                    FontWeight = "500",
                    FontSize = "1.25rem",
                    LineHeight = "1.6",
                    LetterSpacing = ".0075em",
                    TextTransform = "none",
                },
                Subtitle1 = new Subtitle1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Subtitle2 = new Subtitle2Typography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.57",
                    LetterSpacing = ".00714em",
                    TextTransform = "none",
                },
                Body1 = new Body1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.5",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Body2 = new Body2Typography
                {
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                Button = new ButtonTypography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".02857em",
                    TextTransform = "uppercase",
                },
                Caption = new CaptionTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "1.66",
                    LetterSpacing = ".03333em",
                    TextTransform = "none",
                },
                Overline = new OverlineTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "2.66",
                    LetterSpacing = ".08333em",
                    TextTransform = "none",
                },
            },
            ZIndex = new ZIndex()
            {
                AppBar = 1100,
                Dialog = 1400,
                Drawer = 1100,
                Popover = 1200,
                Snackbar = 1500,
                Tooltip = 1600,
            },
        };
    }
}
